version: '3.1'

services:

  mongo:
    image: mongo
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: VU5cwJ3LpWYtzRua7kbKCXM4BndxZsAgHPFe62DqvhSjm8EQNG
    ports:
      - 273:27017
  backbone:
    image: node
    restart: always
    ports:
      - 272:272
    entrypoint: /app/docker/entrypoint.sh
    environment:
      - NODE_ENV=production